/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.j2eecn.mcat.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MeAssetCatCare service. Represents a row in the &quot;MeAssetCatCare&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.j2eecn.mcat.model.impl.MeAssetCatCareModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.j2eecn.mcat.model.impl.MeAssetCatCareImpl}.
 * </p>
 *
 * @author Administrator
 * @see MeAssetCatCare
 * @see com.j2eecn.mcat.model.impl.MeAssetCatCareImpl
 * @see com.j2eecn.mcat.model.impl.MeAssetCatCareModelImpl
 * @generated
 */
public interface MeAssetCatCareModel extends BaseModel<MeAssetCatCare>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a me asset cat care model instance should use the {@link MeAssetCatCare} interface instead.
	 */

	/**
	 * Returns the primary key of this me asset cat care.
	 *
	 * @return the primary key of this me asset cat care
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this me asset cat care.
	 *
	 * @param primaryKey the primary key of this me asset cat care
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this me asset cat care.
	 *
	 * @return the uuid of this me asset cat care
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this me asset cat care.
	 *
	 * @param uuid the uuid of this me asset cat care
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the asset cat care ID of this me asset cat care.
	 *
	 * @return the asset cat care ID of this me asset cat care
	 */
	public long getAssetCatCareId();

	/**
	 * Sets the asset cat care ID of this me asset cat care.
	 *
	 * @param assetCatCareId the asset cat care ID of this me asset cat care
	 */
	public void setAssetCatCareId(long assetCatCareId);

	/**
	 * Returns the group ID of this me asset cat care.
	 *
	 * @return the group ID of this me asset cat care
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this me asset cat care.
	 *
	 * @param groupId the group ID of this me asset cat care
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this me asset cat care.
	 *
	 * @return the company ID of this me asset cat care
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this me asset cat care.
	 *
	 * @param companyId the company ID of this me asset cat care
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this me asset cat care.
	 *
	 * @return the user ID of this me asset cat care
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this me asset cat care.
	 *
	 * @param userId the user ID of this me asset cat care
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this me asset cat care.
	 *
	 * @return the user uuid of this me asset cat care
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this me asset cat care.
	 *
	 * @param userUuid the user uuid of this me asset cat care
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this me asset cat care.
	 *
	 * @return the user name of this me asset cat care
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this me asset cat care.
	 *
	 * @param userName the user name of this me asset cat care
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this me asset cat care.
	 *
	 * @return the create date of this me asset cat care
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this me asset cat care.
	 *
	 * @param createDate the create date of this me asset cat care
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this me asset cat care.
	 *
	 * @return the modified date of this me asset cat care
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this me asset cat care.
	 *
	 * @param modifiedDate the modified date of this me asset cat care
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the asset cat ID of this me asset cat care.
	 *
	 * @return the asset cat ID of this me asset cat care
	 */
	public long getAssetCatId();

	/**
	 * Sets the asset cat ID of this me asset cat care.
	 *
	 * @param assetCatId the asset cat ID of this me asset cat care
	 */
	public void setAssetCatId(long assetCatId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.j2eecn.mcat.model.MeAssetCatCare meAssetCatCare);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.j2eecn.mcat.model.MeAssetCatCare> toCacheModel();

	@Override
	public com.j2eecn.mcat.model.MeAssetCatCare toEscapedModel();

	@Override
	public com.j2eecn.mcat.model.MeAssetCatCare toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}