/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.j2eecn.mcat.model.impl;

import com.j2eecn.mcat.model.MeAssetCatCare;
import com.j2eecn.mcat.service.MeAssetCatCareLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the MeAssetCatCare service. Represents a row in the &quot;MeAssetCatCare&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MeAssetCatCareImpl}.
 * </p>
 *
 * @author Administrator
 * @see MeAssetCatCareImpl
 * @see com.j2eecn.mcat.model.MeAssetCatCare
 * @generated
 */
public abstract class MeAssetCatCareBaseImpl extends MeAssetCatCareModelImpl
	implements MeAssetCatCare {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a me asset cat care model instance should use the {@link MeAssetCatCare} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			MeAssetCatCareLocalServiceUtil.addMeAssetCatCare(this);
		}
		else {
			MeAssetCatCareLocalServiceUtil.updateMeAssetCatCare(this);
		}
	}
}